import { FieldDefinition } from './types';

export const FIELD_GROUPS = [
  'Thông tin Cơ quan',
  'Thông tin Hồ sơ Cơ bản',
  'Thuộc tính Dữ liệu',
  'Chủ sử dụng & Thửa đất',
  'Giấy tờ & Quyết định',
  'Quản lý Lưu trữ',
];

export const LAND_FIELDS: FieldDefinition[] = [
  {
    key: 'maDinhDanh',
    label: 'Mã định danh cơ quan',
    description: 'Mặc định theo mã cơ quan đang được thực hiện số hóa',
    group: FIELD_GROUPS[0],
    defaultValue: 'CQ-01',
  },
  {
    key: 'tenPhong',
    label: 'Tên phông',
    description: 'Nhập tên phông hồ sơ',
    example: '1 Chi nhánh Văn phòng Đăng ký đất đai huyện Tân Phước...',
    group: FIELD_GROUPS[0],
  },
  {
    key: 'tenDonViCungCap',
    label: 'Tên đơn vị cung cấp/đơn vị nộp lưu',
    description: 'Tên cơ quan, địa chỉ, người đại diện, chức vụ, SĐT, email...',
    example: 'Văn phòng Đăng ký đất đai huyện...',
    group: FIELD_GROUPS[0],
  },
  {
    key: 'donViTaoLap',
    label: 'Đơn vị tạo lập dữ liệu',
    description: 'Tên cơ quan, địa chỉ, người đại diện, chức vụ, SĐT, email...',
    group: FIELD_GROUPS[0],
  },
  {
    key: 'loaiDuLieu',
    label: 'Loại dữ liệu',
    description: 'Lĩnh vực dữ liệu',
    defaultValue: 'Dữ liệu lĩnh vực đất đai',
    group: FIELD_GROUPS[0],
  },
  {
    key: 'nhanDe',
    label: 'Nhan đề',
    description: 'Lấy theo thông tin trên bìa hồ sơ',
    group: FIELD_GROUPS[1],
  },
  {
    key: 'chuDe',
    label: 'Chủ đề',
    description: 'Lấy theo thông tin trên bìa hồ sơ',
    group: FIELD_GROUPS[1],
  },
  {
    key: 'tomTat',
    label: 'Tóm tắt',
    description: 'Tóm tắt nội dung chính của hồ sơ',
    type: 'textarea',
    group: FIELD_GROUPS[1],
  },
  {
    key: 'nguonDuLieu',
    label: 'Nguồn dữ liệu',
    description: 'Tên đơn vị thực hiện (VD: Văn phòng ĐKĐĐ tỉnh Tiền Giang)',
    group: FIELD_GROUPS[1],
  },
  {
    key: 'ngayPhatHanh',
    label: 'Ngày phát hành',
    description: 'Lấy theo ngày thực tế phát hành',
    type: 'date',
    group: FIELD_GROUPS[1],
  },
  {
    key: 'donViCungCap',
    label: 'Đơn vị cung cấp',
    description: 'Chỉ ghi tên cơ quan thông tin sau sáp nhập',
    group: FIELD_GROUPS[1],
  },
  {
    key: 'donViLienQuan',
    label: 'Đơn vị liên quan',
    description: 'Các đơn vị phối hợp tạo hồ sơ',
    group: FIELD_GROUPS[1],
  },
  {
    key: 'ngonNgu',
    label: 'Ngôn ngữ',
    description: 'Ngôn ngữ sử dụng trong hồ sơ',
    type: 'select',
    options: ['Tiếng Việt', 'Tiếng Anh', 'Việt Anh', 'Khác'],
    defaultValue: 'Tiếng Việt',
    group: FIELD_GROUPS[2],
  },
  {
    key: 'phamViDuLieu',
    label: 'Phạm vi dữ liệu',
    description: 'Nhập địa danh cũ nếu có',
    group: FIELD_GROUPS[2],
  },
  {
    key: 'khaNangCungCap',
    label: 'Khả năng khai thác',
    description: 'Hình thức cung cấp sử dụng',
    type: 'select',
    options: ['Tra cứu', 'Trích lục', 'Sao y', 'Sao chép', 'Khác'],
    defaultValue: 'Tra cứu',
    group: FIELD_GROUPS[2],
  },
  {
    key: 'ngayGiaoNop',
    label: 'Ngày giao nộp',
    description: 'Lấy theo ngày thực tế bàn giao',
    type: 'date',
    group: FIELD_GROUPS[2],
  },
  {
    key: 'thoiHanBaoQuan',
    label: 'Thời hạn bảo quản',
    description: 'Mặc định vĩnh viễn',
    defaultValue: 'Vĩnh viễn',
    group: FIELD_GROUPS[2],
  },
  {
    key: 'hoTenChuSuDung',
    label: 'Họ tên chủ sử dụng',
    description: 'Danh xưng + Tên đầy đủ',
    example: 'Ông Trần Văn A, Bà Nguyễn Thị B',
    group: FIELD_GROUPS[3],
  },
  {
    key: 'soToBanDo',
    label: 'Số tờ bản đồ',
    description: 'Số tờ bản đồ địa chính',
    type: 'text',
    group: FIELD_GROUPS[3],
  },
  {
    key: 'soThua',
    label: 'Số thửa',
    description: 'Số thứ tự thửa đất trên bản đồ',
    type: 'text',
    group: FIELD_GROUPS[3],
  },
  {
    key: 'loaiDat',
    label: 'Loại đất',
    description: 'Mục đích sử dụng đất (mã loại đất)',
    type: 'text',
    group: FIELD_GROUPS[3],
  },
  {
    key: 'dienTich',
    label: 'Diện tích (m2)',
    description: 'Diện tích của thửa đất',
    type: 'text',
    group: FIELD_GROUPS[3],
  },
  {
    key: 'thongTinThuaDat',
    label: 'Thông tin thửa đất tổng',
    description: 'Dùng khi có nhiều loại đất. Nhập tổng diện tích.',
    example: 'Đất ở: 150m2, Đất vườn: 100m2',
    group: FIELD_GROUPS[3],
    type: 'textarea',
  },
  {
    key: 'soGiayChungNhan',
    label: 'Số GCN',
    description: 'Số Serial trên giấy chứng nhận',
    group: FIELD_GROUPS[4],
  },
  {
    key: 'soQuyetDinh',
    label: 'Số quyết định',
    description: 'Số quyết định liên quan (theo sổ đỏ)',
    group: FIELD_GROUPS[4],
  },
  {
    key: 'ngayCap',
    label: 'Ngày cấp',
    description: 'Ngày cấp giấy chứng nhận (theo sổ đỏ)',
    type: 'date',
    group: FIELD_GROUPS[4],
  },
  {
    key: 'loaiHoSo',
    label: 'Loại hồ sơ',
    description: 'Phân loại loại hình hồ sơ',
    type: 'select',
    options: [
      '1. Hồ sơ đăng ký đất đai, tài sản gắn liền với đất',
      '2. Hồ sơ đăng ký biến động đất đai',
      '3. Hồ sơ cấp đổi GCN',
      '4. Hồ sơ cấp lại GCN'
    ],
    group: FIELD_GROUPS[4],
  },
  {
    key: 'maHoSoLuuTru',
    label: 'Mã hồ sơ lưu trữ',
    description: '[Mã cơ quan].[Năm].[Số thứ tự]',
    example: 'CQ01.2024.0001',
    group: FIELD_GROUPS[5],
  },
  {
    key: 'tieuDeHoSo',
    label: 'Tiêu đề hồ sơ',
    description: 'Lấy theo bìa hồ sơ',
    group: FIELD_GROUPS[5],
  },
  {
    key: 'thoiGianBatDau',
    label: 'Thời gian bắt đầu',
    description: 'Thời điểm bắt đầu hình thành hồ sơ',
    type: 'date',
    group: FIELD_GROUPS[5],
  },
  {
    key: 'thoiGianKetThuc',
    label: 'Thời gian kết thúc',
    description: 'Thời điểm kết thúc hồ sơ',
    type: 'date',
    group: FIELD_GROUPS[5],
  },
  {
    key: 'tongSoTaiLieu',
    label: 'Tổng số tài liệu',
    description: 'Tổng số tài liệu thành phần trong hồ sơ',
    type: 'number',
    group: FIELD_GROUPS[5],
  },
  {
    key: 'soLuongTo',
    label: 'Số lượng tờ',
    description: 'Tổng số tờ của hồ sơ',
    type: 'number',
    group: FIELD_GROUPS[5],
  },
  {
    key: 'soLuongTrang',
    label: 'Số lượng trang',
    description: 'Tổng số trang của hồ sơ',
    type: 'number',
    group: FIELD_GROUPS[5],
  },
  {
    key: 'tinhTrangVatLy',
    label: 'Tình trạng vật lý',
    description: 'Mô tả tình trạng bên ngoài hồ sơ',
    defaultValue: 'Bình thường',
    group: FIELD_GROUPS[5],
  },
  {
    key: 'soKyHieuHoSo',
    label: 'Số ký hiệu',
    description: 'Số và ký hiệu hồ sơ (nếu có)',
    group: FIELD_GROUPS[5],
  },
  {
    key: 'hopSo',
    label: 'Hộp số',
    description: 'Số hộp lưu trữ',
    group: FIELD_GROUPS[5],
  },
  {
    key: 'ke',
    label: 'Kệ',
    description: 'Vị trí kệ lưu trữ',
    group: FIELD_GROUPS[5],
  },
  {
    key: 'khoLuuTru',
    label: 'Kho lưu trữ',
    description: 'Bộ phận/Kho lưu trữ hồ sơ',
    group: FIELD_GROUPS[5],
  },
  {
    key: 'path',
    label: 'Đường dẫn file',
    description: 'Link đến file scan hồ sơ',
    group: FIELD_GROUPS[5],
  },
];
